FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git ca-certificates

ENV GIT_SSL_NO_VERIFY=1
ENV GONOSUMCHECK=*
ENV GONOSUMDB=*
ENV GOINSECURE=*
ENV GOPROXY=direct

WORKDIR /go/migrations

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.3
